// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wDs7k7ubHzuKh3ioqPnFhb
// Component: OLhjxIbbQsnn
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Navbar from "../../Navbar"; // plasmic-import: xhcd-74Zw-KQ/component
import Button from "../../Button"; // plasmic-import: gT-lQgwg5epa/component
import Section from "../../Section"; // plasmic-import: 7SewzomZ1NU7/component
import DiagramCard from "../../DiagramCard"; // plasmic-import: K1w4d9JodYxU/component
import ProductCard from "../../ProductCard"; // plasmic-import: lHslax0KgMt7/component
import DetailAbout from "../../DetailAbout"; // plasmic-import: 1iaabv9YpT7O/component
import PriceSection from "../../PriceSection"; // plasmic-import: 0epNN3jGtaHL/component
import PriceCard from "../../PriceCard"; // plasmic-import: GuyH_uMej2yc/component
import FooterSection from "../../FooterSection"; // plasmic-import: j-RUgUJCGn-G/component
import { useScreenVariants as useScreenVariants_6HNd7CJfhEm } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 6HNd_7CJfhEM/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: wDs7k7ubHzuKh3ioqPnFhb/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: OLhjxIbbQsnn/css
import IconArrowRightsvgIcon from "./icons/PlasmicIcon__IconArrowRightsvg"; // plasmic-import: xHauYQhNUQjY/icon
import diagramsvg6UIqDJhewZcD from "./images/diagramsvg.svg"; // plasmic-import: 6uIqDJhewZcD/picture
import logoHero1PngXvh0PTasl3Zy from "./images/logoHero1Png.png"; // plasmic-import: xvh0pTasl3Zy/picture
import logoHero2PngA4EhQofFfYPg from "./images/logoHero2Png.png"; // plasmic-import: A4ehQofFfYPg/picture
import logoHero3PngSkDyzMJgMy9F from "./images/logoHero3Png.png"; // plasmic-import: SkDyzMJgMy9f/picture
import logoHero4Png5JLsA83GnMaj from "./images/logoHero4Png.png"; // plasmic-import: 5jLsA83GNMaj/picture
import diagramImgsvgWokRiSskXF from "./images/diagramImgsvg.svg"; // plasmic-import: WOKRiSSK_xF-/picture
import ellipseLeftpngOJl94GkJUzh from "./images/ellipseLeftpng.png"; // plasmic-import: OJl94GkJUzh_/picture
import ellipseRightpngHmAic6XsmWp from "./images/ellipseRightpng.png"; // plasmic-import: -hmAic6XsmWp/picture
import terminalpngJWySwY7YcUa3 from "./images/terminalpng.png"; // plasmic-import: JWySwY7YcUa3/picture
import line1PngIl1MY55M4DzH from "./images/line1Png.png"; // plasmic-import: IL1mY55M4DzH/picture
import lineBranchpngD4UFyb5PjCa from "./images/lineBranchpng.png"; // plasmic-import: D4U_Fyb5PjCA/picture
import line2PngUcRuNaiyJxS from "./images/line2Png.png"; // plasmic-import: ucRuNAIY-jxS/picture
import dollarpngHLAeNzGfe3Tf from "./images/dollarpng.png"; // plasmic-import: hLAeNZGfe3Tf/picture
import messagepngYkDBbgaqZfR from "./images/messagepng.png"; // plasmic-import: YK_dBBGAQZfR/picture
import importpngWeaxFt4D6Cj from "./images/importpng.png"; // plasmic-import: WeaxFT4d-6cj/picture
import exportpngJKnW6Vv5QaSp from "./images/exportpng.png"; // plasmic-import: jKnW6vv5QASp/picture
import message2PngR1KeLoo3U63Z from "./images/message2Png.png"; // plasmic-import: r1keLoo3U63z/picture
import message3PngYnRp31YQea7L from "./images/message3Png.png"; // plasmic-import: YnRP31YQea7l/picture
import macbookpng2HfwOpulDrR8 from "./images/macbookpng.png"; // plasmic-import: 2hfwOPULDrR8/picture
import galleri11PngC37MCGqHzaYt from "./images/galleri11Png.png"; // plasmic-import: c37mCGqHzaYT/picture
import galleri12Png6Hu6ZcAyLhpK from "./images/galleri12Png.png"; // plasmic-import: 6HU6ZCAyLhpK/picture
import galleri13PngHthFa5VoFRj from "./images/galleri13Png.png"; // plasmic-import: hthFA5Vo-fRj/picture
import galleri21PngUpNpSZy5MUh from "./images/galleri21Png.png"; // plasmic-import: UpNpS-ZY5MUh/picture
import galleri22PngGh5XYm3PiNyj from "./images/galleri22Png.png"; // plasmic-import: gh5xYm3PiNYJ/picture
import galleri23PngZntePvV1EuKo from "./images/galleri23Png.png"; // plasmic-import: zntePvV1EuKo/picture
import aboutImgpng5Od4MUt4UuKw from "./images/aboutImgpng.png"; // plasmic-import: 5OD4mUT4uuKW/picture
import aboutIpsumpngM2C4GnWhHcDo from "./images/aboutIpsumpng.png"; // plasmic-import: m2c4gnWhHcDo/picture
import backtippngCUyEu3I9UtCk from "./images/backtippng.png"; // plasmic-import: CUyEu3i9utCK/picture
import arrowLeftpngIg2Z7C4LzDv2 from "./images/arrowLeftpng.png"; // plasmic-import: IG2z7C4LzDV2/picture
import arrowRightpng2TnnORrLqIbtm from "./images/arrowRightpng2.png"; // plasmic-import: tnnORrLQIbtm/picture
import pricingImgsvgMUPkQyZpSwva from "./images/pricingImgsvg.svg"; // plasmic-import: mUPkQyZpSwva/picture

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_6HNd7CJfhEm()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Stack__
            as={"div"}
            data-plasmic-name={"headerHeroSection"}
            data-plasmic-override={overrides.headerHeroSection}
            hasGap={true}
            className={classNames(projectcss.all, sty.headerHeroSection)}
          >
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__ikPrz)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__f9Kqt)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__zbF0V)}>
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Analytics for developers can be better"
                      : "Analytics for \ndevelopers can\nbe better"}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ya1Az
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                      : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__vSEze)}
                  >
                    <Button
                      className={classNames("__wab_instance", sty.button__zEJl)}
                      color={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "blueSmall"
                          : "blue"
                      }
                      endIcon={
                        <IconArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg__p61Vo)}
                          role={"img"}
                        />
                      }
                      link={"#"}
                      showEndIcon={true}
                      startIcon={
                        <svg
                          className={classNames(projectcss.all, sty.svg__jlMsC)}
                          role={"img"}
                        />
                      }
                      submitsForm={true}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__svD5S
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Try Demo For Free"
                          : "Try Demo For Free"}
                      </div>
                    </Button>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__vQun7
                      )}
                      color={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "blueBorderSmall"
                          : "blueBorder"
                      }
                      endIcon={
                        <svg
                          className={classNames(projectcss.all, sty.svg__aVRh)}
                          role={"img"}
                        />
                      }
                      link={"#"}
                      startIcon={
                        <svg
                          className={classNames(projectcss.all, sty.svg__gdY9I)}
                          role={"img"}
                        />
                      }
                      submitsForm={true}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fUoMp
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Learn More"
                          : "Learn More"}
                      </div>
                    </Button>
                  </Stack__>
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : false
                  ) ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__lYgqs)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__qOaf
                        )}
                        color={"blueBorder"}
                        endIcon={
                          <svg
                            className={classNames(
                              projectcss.all,
                              sty.svg__lwXsy
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <svg
                            className={classNames(
                              projectcss.all,
                              sty.svg__jufNe
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        {"Learn More"}
                      </Button>
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__iOTl2
                        )}
                        color={"blueBorder"}
                        endIcon={
                          <svg
                            className={classNames(
                              projectcss.all,
                              sty.svg__cwKxr
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <svg
                            className={classNames(
                              projectcss.all,
                              sty.svg__kiDvr
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        {"Learn More"}
                      </Button>
                    </div>
                  ) : null}
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__efSP)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__yLJp3)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "0px"
                        : "661px"
                    }
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    loading={"lazy"}
                    src={{
                      src: diagramsvg6UIqDJhewZcD,
                      fullWidth: 173,
                      fullHeight: 150,
                      aspectRatio: 1.151631
                    }}
                  />
                </div>
              </Stack__>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iL5KY
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Powering with magnificant of Companies"
                  : "Powering with magnificant of Companies"}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__wSNmP)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__lgExE)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "170px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: logoHero1PngXvh0PTasl3Zy,
                    fullWidth: 233,
                    fullHeight: 50,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__mEgia)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "170px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: logoHero2PngA4EhQofFfYPg,
                    fullWidth: 189,
                    fullHeight: 50,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__d61Dx)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "170px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: logoHero3PngSkDyzMJgMy9F,
                    fullWidth: 194,
                    fullHeight: 50,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__tju8Z)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "170px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: logoHero4Png5JLsA83GnMaj,
                    fullWidth: 189,
                    fullHeight: 50,
                    aspectRatio: undefined
                  }}
                />
              </Stack__>
            </div>
          </Stack__>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__eJmFb)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: diagramImgsvgWokRiSskXF,
              fullWidth: 300,
              fullHeight: 100,
              aspectRatio: 2.987552
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img___6SNTi)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"774px"}
            loading={"lazy"}
            src={{
              src: ellipseLeftpngOJl94GkJUzh,
              fullWidth: 469,
              fullHeight: 742,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__uriwg)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: ellipseRightpngHmAic6XsmWp,
              fullWidth: 437,
              fullHeight: 742,
              aspectRatio: undefined
            }}
          />

          <Section
            data-plasmic-name={"diagramSection"}
            data-plasmic-override={overrides.diagramSection}
            className={classNames("__wab_instance", sty.diagramSection)}
            size={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "mobile"
                : undefined
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__tY8P)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__iuvnt
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Lorem ipsum dolor \nsit amet"
                  : "Lorem ipsum dolor \nsit amet"}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nU1Cd
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                  : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."}
              </div>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___1GHyz)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "249px"
                    : "100%"
                }
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: terminalpngJWySwY7YcUa3,
                  fullWidth: 624,
                  fullHeight: 333,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__ni2Ul)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "auto"
                    : "auto"
                }
                loading={"lazy"}
                src={{
                  src: line1PngIl1MY55M4DzH,
                  fullWidth: 11,
                  fullHeight: 150,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___9NDV)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "50px"
                    : "100%"
                }
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: lineBranchpngD4UFyb5PjCa,
                  fullWidth: 100,
                  fullHeight: 100,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__ldeTa)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "auto"
                    : "auto"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "500px"
                    : "770px"
                }
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "auto"
                    : "auto"
                }
                loading={"lazy"}
                src={{
                  src: line2PngUcRuNaiyJxS,
                  fullWidth: 844,
                  fullHeight: 284,
                  aspectRatio: undefined
                }}
              />

              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__tZCyG)}
              >
                <DiagramCard
                  className={classNames(
                    "__wab_instance",
                    sty.diagramCard__ztCXt
                  )}
                />

                <DiagramCard
                  className={classNames(
                    "__wab_instance",
                    sty.diagramCard__bxMwP
                  )}
                />

                <DiagramCard
                  className={classNames(
                    "__wab_instance",
                    sty.diagramCard__v5Bhc
                  )}
                />
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__fzGpO)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__qslR0)}
                  displayHeight={"auto"}
                  displayMaxHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "none"
                  }
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: dollarpngHLAeNzGfe3Tf,
                    fullWidth: 100,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__ltea6)}
                  displayHeight={"auto"}
                  displayMaxHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "none"
                  }
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: messagepngYkDBbgaqZfR,
                    fullWidth: 100,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___0Yn3H)}
                  displayHeight={"auto"}
                  displayMaxHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "none"
                  }
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: importpngWeaxFt4D6Cj,
                    fullWidth: 100,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___5MjN7)}
                  displayHeight={"auto"}
                  displayMaxHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "none"
                  }
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: lineBranchpngD4UFyb5PjCa,
                    fullWidth: 100,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___1BuVz)}
                  displayHeight={"auto"}
                  displayMaxHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "none"
                  }
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: exportpngJKnW6Vv5QaSp,
                    fullWidth: 100,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__qKxzB)}
                  displayHeight={"auto"}
                  displayMaxHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "none"
                  }
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: message2PngR1KeLoo3U63Z,
                    fullWidth: 100,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__nwrzU)}
                  displayHeight={"auto"}
                  displayMaxHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "none"
                  }
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: message3PngYnRp31YQea7L,
                    fullWidth: 100,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />
              </Stack__>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__g8Ixu
                )}
              >
                {"Lorem ipsum dolor \nsit amet"}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iRuvT
                )}
              >
                {
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                }
              </div>
            </div>
          </Section>
          <Section
            data-plasmic-name={"deviceSection"}
            data-plasmic-override={overrides.deviceSection}
            background={"dark"}
            className={classNames("__wab_instance", sty.deviceSection)}
            size={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "mobile"
                : undefined
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__yfFr)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__dYhIj
                )}
              >
                {"Lorem ipsum dolor sit amet"}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aSmQo
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do \neiusmod tempor incididunt ut labore et dolore magna aliqua."
                  : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do \neiusmod tempor incididunt ut labore et dolore magna aliqua."}
              </div>
            </div>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__bh8GA)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "360px"
                  : "100%"
              }
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: macbookpng2HfwOpulDrR8,
                fullWidth: 900,
                fullHeight: 565,
                aspectRatio: undefined
              }}
            />
          </Section>
          <Section
            data-plasmic-name={"gallerySection"}
            data-plasmic-override={overrides.gallerySection}
            className={classNames("__wab_instance", sty.gallerySection)}
            size={"fullContentGallery"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__uw91H)}>
              <div className={classNames(projectcss.all, sty.columns__mjC8Z)}>
                <div className={classNames(projectcss.all, sty.column__enhXy)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__qutoR)}
                    displayHeight={"100%"}
                    displayMaxHeight={"300px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: galleri11PngC37MCGqHzaYt,
                      fullWidth: 700,
                      fullHeight: 300,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__vDlR7)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__cTwA9)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: galleri12Png6Hu6ZcAyLhpK,
                      fullWidth: 700,
                      fullHeight: 300,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__jxb2V)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__fRc0D)}
                    displayHeight={"100%"}
                    displayMaxHeight={"300px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: galleri13PngHthFa5VoFRj,
                      fullWidth: 700,
                      fullHeight: 300,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.columns__yx9XQ)}>
                <div className={classNames(projectcss.all, sty.column__bivPn)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__esLwQ)}
                    displayHeight={"100%"}
                    displayMaxHeight={"300px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: galleri21PngUpNpSZy5MUh,
                      fullWidth: 700,
                      fullHeight: 300,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__zoZrj)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__nWwtQ)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: galleri22PngGh5XYm3PiNyj,
                      fullWidth: 700,
                      fullHeight: 300,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column___1HIsW)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__ftUgl)}
                    displayHeight={"100%"}
                    displayMaxHeight={"300px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: galleri23PngZntePvV1EuKo,
                      fullWidth: 700,
                      fullHeight: 300,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </div>
          </Section>
          <Section
            data-plasmic-name={"productSection"}
            data-plasmic-override={overrides.productSection}
            className={classNames("__wab_instance", sty.productSection)}
            size={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "mobile"
                : undefined
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__s2Ma2)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__i7QYe
                )}
              >
                {"Lorem ipsum dolor sit amet"}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__utv8P
                )}
              >
                {
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do \neiusmod tempor incididunt ut labore et dolore magna aliqua."
                }
              </div>
              <Button
                className={classNames("__wab_instance", sty.button__aNfMk)}
                color={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "blue"
                    : "blue"
                }
                endIcon={
                  <svg
                    className={classNames(projectcss.all, sty.svg__bgPbu)}
                    role={"img"}
                  />
                }
                link={"#"}
                startIcon={
                  <svg
                    className={classNames(projectcss.all, sty.svg__o6OiM)}
                    role={"img"}
                  />
                }
                submitsForm={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wuQ64
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "Get Started"
                    : "Get Started"}
                </div>
              </Button>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__yjuNl)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__yosHu
                  )}
                />

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__uz64X
                  )}
                />
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__b0Dor)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__d8UYz
                  )}
                />

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__hqa4X
                  )}
                />
              </Stack__>
            </div>
          </Section>
          <Section
            data-plasmic-name={"aboutSection"}
            data-plasmic-override={overrides.aboutSection}
            background={"dark"}
            className={classNames("__wab_instance", sty.aboutSection)}
            size={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "mobile"
                : undefined
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox___79LG5)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__ozo7H
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "What people say \nabout us"
                  : "What people say about us"}
              </h2>
              <div className={classNames(projectcss.all, sty.freeBox__evbVg)}>
                <div className={classNames(projectcss.all, sty.freeBox__kCwR)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___1OVFk)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "339px"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: aboutImgpng5Od4MUt4UuKw,
                      fullWidth: 400,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__ixdZ)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___16ZMr
                    )}
                  >
                    {"Michael Justin"}
                  </h2>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__kkjPr)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__wGcSu)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: aboutIpsumpngM2C4GnWhHcDo,
                        fullWidth: 152,
                        fullHeight: 40,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bzK54
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "CEO Company"
                        : "CEO Company"}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___6YK2G)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__yGo4H)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "auto"
                          : "auto"
                      }
                      loading={"lazy"}
                      src={{
                        src: backtippngCUyEu3I9UtCk,
                        fullWidth: 34,
                        fullHeight: 32,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__m3Ce
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                      : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."}
                  </div>
                </div>
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__z73V)}
              >
                <DetailAbout
                  className={classNames(
                    "__wab_instance",
                    sty.detailAbout__p4CNc
                  )}
                />

                <DetailAbout
                  className={classNames(
                    "__wab_instance",
                    sty.detailAbout__lpkgD
                  )}
                />

                <DetailAbout
                  className={classNames(
                    "__wab_instance",
                    sty.detailAbout__sYt7W
                  )}
                />
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__jAwcy)}
              >
                <DetailAbout
                  className={classNames(
                    "__wab_instance",
                    sty.detailAbout__no6WB
                  )}
                />

                <DetailAbout
                  className={classNames(
                    "__wab_instance",
                    sty.detailAbout__x5JtF
                  )}
                />

                <DetailAbout
                  className={classNames(
                    "__wab_instance",
                    sty.detailAbout__iqGRu
                  )}
                />
              </Stack__>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__eO3U2)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: arrowLeftpngIg2Z7C4LzDv2,
                  fullWidth: 24,
                  fullHeight: 24,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__eyVg7)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: arrowRightpng2TnnORrLqIbtm,
                  fullWidth: 24,
                  fullHeight: 24,
                  aspectRatio: undefined
                }}
              />
            </div>
          </Section>
          <PriceSection
            data-plasmic-name={"priceSection"}
            data-plasmic-override={overrides.priceSection}
            className={classNames("__wab_instance", sty.priceSection)}
          />

          <Section
            data-plasmic-name={"startSection"}
            data-plasmic-override={overrides.startSection}
            className={classNames("__wab_instance", sty.startSection)}
            size={"fullContentWidth"}
          >
            <div className={classNames(projectcss.all, sty.freeBox___5B4Uv)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__iNc1)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: pricingImgsvgMUPkQyZpSwva,
                  fullWidth: 300,
                  fullHeight: 67,
                  aspectRatio: 4.468401
                }}
              />

              <div className={classNames(projectcss.all, sty.columns__aDuK2)}>
                <div className={classNames(projectcss.all, sty.column___0Khjv)}>
                  <h3
                    data-plasmic-name={"h3"}
                    data-plasmic-override={overrides.h3}
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Start using our product today"
                      : "Start using our product today"}
                  </h3>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__t4Ukg
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Faster than free analytics tools. Access to all your data, with respect to the privacy of your users."
                      : "Faster than free analytics tools. Access to all your data, with respect to the privacy of your users."}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__dZn2P)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__vndp5)}
                    color={"white"}
                    endIcon={
                      <svg
                        className={classNames(projectcss.all, sty.svg__vNhzs)}
                        role={"img"}
                      />
                    }
                    link={"#"}
                    startIcon={
                      <svg
                        className={classNames(projectcss.all, sty.svg__eh4Yt)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iuNi9
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Get Started"
                        : "Get Started"}
                    </div>
                  </Button>
                </div>
              </div>
            </div>
          </Section>
          <Section
            data-plasmic-name={"pricingSection"}
            data-plasmic-override={overrides.pricingSection}
            className={classNames("__wab_instance", sty.pricingSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__p8XMo)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns___9SyLq)}
              >
                <div className={classNames(projectcss.all, sty.column__zHnlu)}>
                  <PriceCard
                    borders={["flatLeft"]}
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard___1Nkb
                    )}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__iApsh)}>
                  <PriceCard
                    borders={["flatCenter"]}
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__imKit
                    )}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__jez42)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fZkXe
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "We Recommended"
                        : "We Recommended"}
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__yzdgf)}>
                  <PriceCard
                    borders={["flatRight"]}
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__qpceN
                    )}
                  />
                </div>
              </Stack__>
            </div>
          </Section>
          <FooterSection
            data-plasmic-name={"footerSection"}
            data-plasmic-override={overrides.footerSection}
            className={classNames("__wab_instance", sty.footerSection)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerHeroSection",
    "navbar",
    "h1",
    "diagramSection",
    "deviceSection",
    "gallerySection",
    "productSection",
    "aboutSection",
    "priceSection",
    "startSection",
    "h3",
    "pricingSection",
    "footerSection"
  ],

  headerHeroSection: ["headerHeroSection", "navbar", "h1"],
  navbar: ["navbar"],
  h1: ["h1"],
  diagramSection: ["diagramSection"],
  deviceSection: ["deviceSection"],
  gallerySection: ["gallerySection"],
  productSection: ["productSection"],
  aboutSection: ["aboutSection"],
  priceSection: ["priceSection"],
  startSection: ["startSection", "h3"],
  h3: ["h3"],
  pricingSection: ["pricingSection"],
  footerSection: ["footerSection"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    navbar: makeNodeComponent("navbar"),
    h1: makeNodeComponent("h1"),
    diagramSection: makeNodeComponent("diagramSection"),
    deviceSection: makeNodeComponent("deviceSection"),
    gallerySection: makeNodeComponent("gallerySection"),
    productSection: makeNodeComponent("productSection"),
    aboutSection: makeNodeComponent("aboutSection"),
    priceSection: makeNodeComponent("priceSection"),
    startSection: makeNodeComponent("startSection"),
    h3: makeNodeComponent("h3"),
    pricingSection: makeNodeComponent("pricingSection"),
    footerSection: makeNodeComponent("footerSection"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Home",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
